#ifndef ERROR_H
#define ERROR_H

typedef enum
{
    ERR_NONE = 0,
    ERR_FAILED_GENERATE_RANDOM_SEED,
    ERR_FAILED_DECODE_HEXSEED,
    ERR_INVALID_SIGB_LENGTH,
    ERR_INVALID_CONTEXT_LENGTH,
    ERR_INVALID_SEED_LENGTH,
    ERR_INVALID_LENGTH,
    ERR_DECODE_HEX_STRING,
    ERR_INVALID_DESCRIPTOR,
    ERR_INVALID_MESSAGE
} ErrorCode;

#endif